{% set name = "Magnipore" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # path: ../
  git_rev: v{{ version }}
  git_url: https://github.com/JannesSP/{{ name|lower }}.git

advice.detachedHead: false

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.9
    - numpy>=1.23
    - setuptools
  run:
    - python>=3.9
    - h5py>=3.7
    - biopython>=1.80
    - mafft>=7.508
    - matplotlib>=3.6.2
    - numpy>=1.23
    - scipy>=1.9
    - nanopolish>=0.14
    - minimap2>=2.24
    - pandas>=1.5
    - seaborn>=0.12
    - psutil>=5.9
    - hdf5plugin>=3.3.1
    - ont_vbz_hdf_plugin>=1.0.1

test:
  imports:
    - {{ name|lower }}
  commands:
    - magnipore --help
    - nanosherlock --help

about:
  home: https://github.com/JannesSP/{{ name|lower }}
  license: GNU General Public License v3.0
  license_family: GPL
  license_file: LICENSE 
  summary: "Magnipore compares two ONT sequences samples for differential signals cause by mutations and modifications"
